---
title: "Graphs"
author: "Aleksandr Matrunich"
date: "02/13/2015"
output: html_document
---

```{r}
library(dplyr)
library(stringr)
library(igraph)
library(reshape2)
# library(fclhs)
devtools::load_all("/home/sas/fao/fclhs/")

areacodes2names <- function(code) {
  factor(code,
         levels = unique(code),
         labels = sapply(unique(code), 
                         function(x) {
                           faoareanames$name[faoareanames$fao == x]
                           }))
  }
  
#datafile <- "/home/sas/trade/rf/world_TF_comp.csv.gz"
datafile <- "/home/sas/0mc/projects/rom_fao_trade/sources/world_TF_comp.csv"
data <- read.table(datafile, 
                   header = T, 
                   sep = ",",
                   nrows = 1191653,
#                    nrows = 1000,
                   stringsAsFactors = F,
                   colClasses = c("integer", 
                                  "integer",
                                  "character",
                                  "integer",
                                  "integer",
                                  "numeric",
                                  "numeric",
                                  "numeric",
                                  "integer",
                                  "integer")) %>%
  rename(hs      = hs_code,
         fcl     = fcl_code,
         qty     = source.orig_qty,
         qty2    = source.other_qty,
         value   = source.value,
         qty.fcl = valid.qty,
         vl.fcl  = valid.value) %>%
  mutate(reporter = areacodes2names(reporter),
         partner  = areacodes2names(partner),
         hs6      = factor(stringr::str_extract(hs, "^.{6}")),
         fcl      = factor(fcl),
         flow     = factor(flow),
         qty2     = qty2,
         value    = value) %>%
  select(-hs) %>%
  rename(hs = hs6)


```


```{r}
g1 <- data.frame(
  from = c("u", "u", "u", "m", "m", "m", "hs1", "hs2", "hs3"),
  to   = c("hs1", "hs2", "hs3", "hs1", "hs2", "hs3", "f1", "f2", "f3")) %>%
  graph.data.frame()

plot(g1)
```



Don't use conv.prop(), as prop.table() kills grouping in dplyr.
```{r}
conv.prop <- function(data, dec = 2) {
  data %>%
    select_(~hs, ~fcl, ~qty, ~qty2, ~qty.fcl, ~value, ~vl.fcl) %>%
    lapply(function(x) {
      if(is.character(x) | is.factor(x)) return(x) # Don't get props of character values
      round(prop.table(x), dec)
  }) %>%
    as.data.frame()
  }
  
data %>%
  rename(hs = hs6) %>%
  conv.prop





d %>%
  filter(vdif < -5)

d <- data %>%
  filter(reporter == "Australia") %>%
  mutate(hs = as.character(hs)) %>%
#  plyr::ddply(c("flow", "partner"), function(x) {
  plyr::ddply(c("flow", "partner"), function(x) {
    x <- x %>%
      left_join(linksgroups(x$hs, x$fcl), by = 'hs')
    
    prop <- function(x) round(x / sum(as.numeric(x)), 2)
    
    x %>%
      group_by_(~membership) %>%
      mutate_(qty     = ~prop(qty),
              qty2    = ~prop(qty2),
              value   = ~prop(value),
              qty.fcl = ~prop(qty.fcl),
              vl.fcl  = ~prop(vl.fcl))
    })

x %>%
  group_by(membership) %>%
  mutate(qty = qty / sum(qty))

    conv.prop()

data <- data %>%
  left_join(linksgroups(data$hs, data$fcl), by = 'hs')  

d1 <- data %>%
  group_by(flow, reporter, partner, membership) %>%
  mutate_(qty     = ~prop(qty),
          qty2    = ~prop(qty2),
          value   = ~prop(value),
          qty.fcl = ~prop(qty.fcl),
          vl.fcl  = ~prop(vl.fcl))

table(d1$membership)

d1 %>%
  ungroup() %>%
  select(fcl, hs, membership) %>%
  distinct() %>%
  group_by(membership) %>%
  summarize(n = n()) %>%
  filter(n == 5)

d1 %>%
  group_by(flow, reporter, partner) %>%
  filter(membership == 10,
         reporter   == "Australia") %>%
  mutate(link = paste0(hs, "_", fcl),
         qdif = qty2 - qty.fcl,
         vdif = value - vl.fcl) %>%
  ggplot(aes(link, vdif)) + 
  geom_bar(stat = "identity") +
  facet_wrap(~ partner) +
  scale_y_continuous(labels = percent, limits = 0:1)

d2 <- d1 %>%
  group_by(flow, reporter, partner, membership) %>%
    mutate(qdif = qty2 - qty.fcl,
           vdif = value - vl.fcl) %>%
  summarize(quan.sd = sd(qdif, na.rm = T),
         val.sd = sd(vdif, na.rm = T)) 

d2 %>%
  group_by(flow) %>%
  summarize(q = mean(quan.sd, na.rm = T),
            v = mean(val.sd, na.rm = T))

d2 %>%
  group_by(reporter) %>%
  summarize(q = mean(quan.sd, na.rm = T),
            v = mean(val.sd, na.rm = T)) %>%
  reshape2::melt(value.name = "mean.sd", variable.name = "item") %>%
  ggplot(aes(mean.sd, color = item)) + geom_density()
```


```{r}

groups <- linksgroups(as.character(data$hs), as.character(data$fcl))

#############
## Chekings of eqalitiy of value/quantity on both sides
##############
d <- data %>%
  filter(reporter == "Australia" &
           flow == 1) %>%
  mutate(hs = as.character(hs)) %>%
  left_join(groups, by = 'hs') %>%
  mutate(qty2  = round(qty2 / 1000, 0),
         value = round(value / 1000, 0)) %>%
  group_by(flow, reporter, partner, membership) %>%
  summarise(qty     = sum(qty, na.rm = T),
            qty2    = sum(qty2, na.rm = T),
            value   = sum(value, na.rm = T),
            qty.fcl = sum(qty.fcl, na.rm = T),
            vl.fcl  = sum(vl.fcl, na.rm = T),
            q2dif   = (qty2 - qty.fcl) / qty2,
            vdif    = (value - vl.fcl) / value)

ggplot(d, aes(q2dif)) + geom_density()
```

Add membership info to data
```{r}

prop <- function(x) round(x / sum(as.numeric(x), na.rm = T), 2)

data1 <- data %>%
  filter(reporter == "Australia" &
           flow == 1) %>%
  mutate(hs = as.character(hs)) %>%
  left_join(groups, by = 'hs') %>%
  mutate(qty2  = round(qty2 / 1000, 0),
         value = round(value / 1000, 0)) %>%
  group_by(flow, reporter, partner, membership) %>%
  mutate_(qty     = ~prop(qty),
          qty2    = ~prop(qty2),
          value   = ~prop(value),
          qty.fcl = ~prop(qty.fcl),
          vl.fcl  = ~prop(vl.fcl))

```

Check for rows with duplicated attributes. Not finished

```{r}

data %>%
  filter(reporter == "Australia" &
           flow == 1) %>%
  mutate(hs = as.character(hs)) %>%
  left_join(groups, by = 'hs') %>%
  group_by(flow, reporter, partner, membership ) %>%
```

Number of items on both sides to check how they spread value/quantity in fuzzy links.

```{r}


data1 <- data %>%
  filter(reporter == "Australia" &
           flow == 1) %>%
  mutate(hs = as.character(hs)) %>%
  left_join(groups, by = 'hs') %>%
  left_join(data %>%
              filter(reporter == "Australia" &
                       flow == 1) %>%
              mutate(hs = as.character(hs)) %>%
              left_join(groups, by = 'hs') %>%
              group_by(flow, reporter, partner, membership) %>%
              summarize(n_hs = length(unique(hs)),
                        n_fcl = length(unique(fcl))) %>%
              ungroup()) %>%
  select(reporter, partner, hs, fcl, qty2, qty.fcl, value, vl.fcl, qty, membership, n_hs, n_fcl) %>%
  filter(partner == "Austria" & membership == 10) %>%
  mutate(qty2 = round(qty2 / 1000),
         value = round(value / 1000)) %>%

```


```{r}
g1 <- data.frame(
  from = c("hs3"),
  to   = c("f1", "f2", "f3")) %>%
  graph.data.frame()

g2 <- data.frame(
  from = c("hs3"),
  to   = c("f1", "f2", "f3")) %>%
  graph.data.frame()



V(g1)$class <- ""
V(g1)[1]$class <- "HS"
V(g1)[2:4]$class <- "FCL"
V(g1)[class == "HS"]$color <- "blue"
V(g1)[class == "FCL"]$color <- "red"
plot(g1)
vcount(g1)
V(g1)[class == "FCL"]
length(V(g1)[class == "FCL"])
```

Creating of list of bipartite graphs

```{r}
graphs_list <- data1 %>%
  mutate(fcl = as.character(fcl)) %>%
  plyr::dlply(c('flow', 'reporter', 'partner', 'membership'), 
              function(d) {nodes <- d %>%
                             select(fcl, hs) %>%
                             reshape2::melt(measure.vars = c('fcl', 'hs'), 
                                        value.name = "code", 
                                        variable.name = "class") %>%
                             mutate(type = ifelse(class == "fcl", T, F))
                           
                           links <- d %>% select(hs, fcl)
                           
#                            return(list(nodes, links))
                           
                           g <- igraph::graph.data.frame(links, 
                                                         directed = T, 
                                                         vertices = nodes)
                           
                           g
                           })
                                        
                             


```

