---
title: "R SWS"
author: "Alexander Matrunich"
date: "12/10/2014"
output: html_document
---

http://hqlqasws1.hq.un.fao.org:8080/sws/
From Nick: 16cc5aef-7b7f-43dd-af94-1660759ddd19
My first: 3870d0bb-2a46-4525-ba44-d9d246ecf502
By example from Nick: 8b9583d7-c691-4239-8ded-432a85e1ffae

```{r loadfaosws}
library(faosws)
library(faoswsUtil)
```

```{r}
GetTestEnvironment(
"https://hqlqasws1.hq.un.fao.org:8181/sws",
"3870d0bb-2a46-4525-ba44-d9d246ecf502")
```

```{r}
library(RCurl)
url <- "https://hqlqasws1.hq.un.fao.org:8181/sws/rest/r/computationParameters/3870d0bb-2a46-4525-ba44-d9d246ecf502"
ch <- getCurlHandle()
response <- getURL(url = url, curl = ch, verbose = TRUE, 
                   noproxy = TRUE, ssl.verifypeer = FALSE, 
                   sslcert = "/home/sas/.R/client.crt", 
                   sslkey = "/home/sas/.R/client.key", ssl.verifyhost = 2, 
                   httpheader = c(Accept = "application/json", `Content-Type` = "application/json"))
```

```{r}
data <- GetData(
key = swsContext.datasets[[1]],
flags = TRUE, normalized = TRUE)
print(data)
```


https://github.com/mkao006/sws_trade/blob/master/tests/get_trade_data.R

```{r}
reportingCountryVar = "reportingCountryM49"
partnerCountryVar = "partnerCountryM49"
yearVar = "timePointYears"
itemVar = "measuredItemHS"
elementVar = "measuredElementTrade"
valuePrefix = "Value_"
flagPrefix = "flagTrade_"
## flagObsPrefix = "flagObservationStatus_"
## flagMethodPrefix = "flagMethod_"
reverseTradePrefix = "reverse_"

allReportingCountryCode =
    GetCodeList(dmn, dtset, dimension = "reportingCountryM49")

itemstree <- GetCodeTree(dmn, dtset, dimension = itmvar)
itemslist <- GetCodeList(dmn, dtset, dimension = itmvar)


cerealItemCode <- adjacent2edge(codetree)[parent == "10", children]

dmn    <- "trade"
dtset  <- "ct_raw_tf"
rtvar  <- "reportingCountryM49"
ptvar  <- "partnerCountryM49"
itmvar <- "measuredItemHS"
elevar <- "measuredElementTrade"
yrvar  <- "timePointYears"

dms <- list(Dimension(name = rtvar,
                      keys = "484"),
            Dimension(name = ptvar,
                      keys = "842"),
            Dimension(name = itmvar,
                      keys = "010110"),
            Dimension(name = elevar,
                      keys = "5621"),
            Dimension(name = yrvar, 
                      keys = "2011"))

k <- DatasetKey(domain     = dmn,
                dataset    = dtset,
                dimensions = dms)

d <- GetData(key = k,
             normalized = T, 
             pivoting = c(Pivoting(code = rtvar),
                          Pivoting(code = ptvar),
                          Pivoting(code = itmvar),
                          Pivoting(code = elevar),
                          Pivoting(code = yrvar)
                          ))

             
```

```{r}
yearslist <- GetCodeList(dmn, dtset, dimension = yrvar)

getswsct(area = 484, partner = 842, year = 2011)

elelist <- GetCodeList(dmn, dtset, dimension = elevar)

if(!ping("hqlqasws1.hq.un.fao.org")) startjnc()

fclhs::getunct(484, 2011, 842) %>% filter(hs == "010110")
x <- getswsct(area = 484, 
              year = 2011, 
              partner = 842, 
              item = "010110")
```


